spring:
  application:
    name: ossdoctor

  # 데이터베이스 설정 (H2 - 임시 테스트용)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 Console 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

# JWT 설정
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# 프론트엔드 URL 설정
app:
  frontend:
    url: ${FRONTEND_URL}

# GitHub API 설정
github:
  token: ${GITHUB_TOKEN}
  api:
    base-url: https://api.github.com
    graphql-url: https://api.github.com/graphql
    rate-limit-max-retries: 3
    cache-expiry-minutes: 10
    timeout-seconds: 30
